### ISSUE TITLE
On reload reset to default on the SaveDataManager

### ISSUE THREAD

**Issue by NicolasSpinosa** [IsaacScript/isaacscript-common#11]
Hi Zamiel! I just come with a little suggestion that might be neat, have to wait to see what you think.

As the tittle implies, it would be nice for the Save Data Manager to include another type of reset that would restore the data to default each time you reload a save.

Of course, this could seem unnesesary since you can manually do that on a POST_GAME_STARTED callback for any feature that you need and this isn't a kind of data that would be stored to disk, but since it's said that you can use the feature to manage your data resets even if you don't want/need to save it, I think it would be nice for the Save Data Manager to take care of this for the user.

**Comment by Zamiell** [comment]
hi nicolas, if you want you can join the discord and we can chat about it

**Comment by NicolasSpinosa** [comment]
I'm NFrost, I just don't know how to change my name hahaha.

**Comment by Zamiell** [comment]
I added a `saveDataManagerReset` helper function that will allow end-users to force the save data manager to reset a specific set of variables.
